# Data Preprocessing 

**Importing Libraries**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

**Importing Dataset**

In [2]:
df=pd.read_csv("Breast cancer_data.csv")
df.replace('?',-99999,inplace=True)
df.drop(['id'],1,inplace=True)
X=df.iloc[:, :-1].values
y=df.iloc[:, -1].values

<ipython-input-2-3b56770a1945>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df.drop(['id'],1,inplace=True)


In [3]:
print(X)

[[5 1 1 ... 3 1 1]
 [5 4 4 ... 3 2 1]
 [3 1 1 ... 3 1 1]
 ...
 [5 10 10 ... 8 10 2]
 [4 8 6 ... 10 6 1]
 [4 8 8 ... 10 4 1]]


In [4]:
print(y)

[0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1
 0 1 1 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 0 0 1 0 1
 1 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 1 1 1 0 1 0
 1 1 1 0 0 0 1 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0
 0 1 0 1 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 1
 0 1 1 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 1 0 1 1 1 0 0 1 0 0 1
 1 1 1 0 1 1 0 1 1 1 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 0
 0 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0 0 1 1 0 1
 0 0 0 1 1 0 1 0 1 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 0 1 0 1 1 1 0 0
 1 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 0 1 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0
 0 0 0 0 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 0 1 1 0 0 0 1 1 1 0 1 0 

 **Splitting data into Test set and Training set** 

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.35, random_state = 42)

**Feature Scaling**

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [7]:
print(X_train)

[[-1.25811098 -0.71205673 -0.76617475 ... -0.98624168 -0.60836032
  -0.34094267]
 [ 1.22683414  0.27958056  0.2420668  ... -0.17947821  0.06283187
  -0.34094267]
 [ 0.51684982  2.26285512  0.57814732 ...  1.03066698  2.41200454
  -0.34094267]
 ...
 [ 1.22683414  0.27958056  1.25030836 ... -0.17947821  2.07640844
   0.28827673]
 [ 1.93681846  1.6017636   2.25854991 ...  0.62728525 -0.60836032
  -0.34094267]
 [-0.1931345  -0.71205673 -0.43009423 ... -0.17947821 -0.60836032
  -0.34094267]]


In [8]:
print(X_test)

[[-1.25811098 -0.71205673 -0.43009423 ... -0.98624168 -0.60836032
  -0.34094267]
 [-0.1931345  -0.71205673 -0.76617475 ... -0.58285995 -0.60836032
  -0.34094267]
 [-0.54812666 -0.71205673 -0.76617475 ... -0.17947821 -0.60836032
  -0.34094267]
 ...
 [-1.25811098 -0.71205673 -0.76617475 ... -0.98624168 -0.60836032
  -0.34094267]
 [ 1.22683414  0.94067208  1.25030836 ... -0.17947821  0.39842796
   0.28827673]
 [-0.54812666  0.61012632  1.25030836 ...  1.43404871  2.41200454
   3.43437372]]


**Principle component analysis**

In [9]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_train = pca.fit_transform(X_train)
X_test = pca.fit_transform(X_test)
explained_variance=pca.explained_variance_ratio_


**Fitting KNN to the Training set**

In [10]:

from sklearn.neighbors import KNeighborsClassifier
knn = []
for i in range(1,21):
            
    classifier = KNeighborsClassifier(n_neighbors=i)
    trained_model=classifier.fit(X_train,y_train)
    trained_model.fit(X_train,y_train )

**Predicting the test results**

In [11]:
    y_pred = classifier.predict(X_test)

**Making Confusion Matrix**

In [12]:
from sklearn.metrics import confusion_matrix
    
cm_KNN = confusion_matrix(y_test, y_pred)
print(cm_KNN)
print("Accuracy score of train KNN")
print(accuracy_score(y_train, trained_model.predict(X_train))*100)
    
print("Accuracy score of test KNN")
print(accuracy_score(y_test, y_pred)*100)

  

[[160   4]
 [  3  78]]
Accuracy score of train KNN
96.0352422907489
Accuracy score of test KNN
97.14285714285714


**Fitting SVM to the Training set**

In [13]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)

trained_model=classifier.fit(X_train,y_train)
trained_model.fit(X_train,y_train )

SVC(kernel='linear', random_state=0)

**Predicting the Test set results**

In [14]:
y_pred = classifier.predict(X_test)

**Making the Confusion matrix**

In [15]:
from sklearn.metrics import confusion_matrix
cm_SVM = confusion_matrix(y_test, y_pred)
print(cm_SVM)
print("Accuracy score of train SVM")
print(accuracy_score(y_train, trained_model.predict(X_train))*100)

print("Accuracy score of test SVM")
print(accuracy_score(y_test, y_pred)*100)

[[160   4]
 [  4  77]]
Accuracy score of train SVM
96.47577092511013
Accuracy score of test SVM
96.73469387755102
